apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
        env: demo
    spec:
      volumes:
        - name: config-template
          configMap:
            name: alertmanager-config
        - name: config
          emptyDir: {}
        - name: secret
          secret:
            secretName: alertmanager-secret
      initContainers:
        - name: render-config
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              sed \
                -e "s/__SMTP_USERNAME__/$(cat /secrets/smtp_username)/" \
                -e "s/__SMTP_PASSWORD__/$(cat /secrets/smtp_password)/" \
                /template/alertmanager.yml > /config/alertmanager.yml
          volumeMounts:
            - name: config-template
              mountPath: /template
            - name: config
              mountPath: /config
            - name: secret
              mountPath: /secrets
      containers:
        - name: alertmanager
          image: prom/alertmanager
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
