apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres-namespace
spec:
  serviceName: "postgres"
  replicas: 3
  selector:
    matchLabels:
      app: postgres
      env: demo
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-sec
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-sec
                  key: password
            - name: POSTGRES_DB
              value: sampledb
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-pvc
        namespace: postgres-namespace
        labels:
          app: postgres
          env: demo
      # spec:
        # accessModes:
        #   - ReadWriteOnce
        # resources:
        #   requests:
        #     storage: 1Gi
        # storageClassName: manual
        # selector:
        #   matchLabels:
        #     app: postgres
        #     env: demo  # replace with your actual storage class