apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres-namespace
  labels:
    role: postgres
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      name: postgres-pod
      role: database
  template:
    metadata:
      labels:
        name: postgres-pod
        role: database
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        imagePullPolicy: Always
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-sec
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-sec
                key: password
          - name: POSTGRES_DB
            value: sampledb
        volumeMounts:
          - name: postgres-pv-storage
            mountPath: /var/lib/postgresql/data
        ports:
        - containerPort: 5432
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - pg_isready -U postgres
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - pg_isready -U postgres
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
      volumes:
        - name: postgres-pv-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---