apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres-namespace
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
    role: database